.PHONY: a b c d e f
a:
	cd a && make
b:
	cd b && make
c:
	cd c && make
d:
	cd d && make
e:
	cd e && make
f:
	cd f && make

clean:
	cd a && make clean
	cd b && make clean
	cd c && make clean
	cd d && make clean
	cd e && make clean
	cd f && make clean
