name:                agc029
version:             0.1.0.0
license:             BSD3
author:              maton
maintainer:          automatonix@gmail.com

source-dirs: .

dependencies:
- base >= 4.7 && < 5
- containers

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  a:
    main:                Main.hs
    source-dirs:         a
  b:
    main:                Main.hs
    source-dirs:         b
  c:
    main:                Main.hs
    source-dirs:         c
  d:
    main:                Main.hs
    source-dirs:         d
